# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            avian-AF • camera log
tagline:          "camera log"
description:      'camera log & raw notes'
url:              https://universe-7.github.io/camera-log
baseurl:          /universe-7.github.io/camera-log

author:
  name:           'Pete Deevakul'
  url:            https://pdpd.org           

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/universe-7/camera-log